### PR TITLE
fix(wordpress) efs and rds inbound rules create fail.

### LINKED ISSUE #38: [wordpress] efs and rds inbound rules create fail
efs and rds inbound rules create fail.

### PR DESCRIPTION
**Pull request by neilkuan**
Fixes #38

### CODE REVIEW

File: src/wordpress.ts [hunk 1]
```diff
@@ -199,7 +165,8 @@ export class WordPress extends cdk.Construct {
       sourceVolume: volumeName,
     });
 
-    filesystem.connections.allowFrom(this.svc.service[0], ec2.Port.tcp(2049));
+    filesystem.connections.allowFrom( new ec2.Connections({ securityGroups: this.svc.service[0].connections.securityGroups }), ec2.Port.tcp(2049), 'allow wordpress to connect efs');
```
Comment (pahud) [inline src/wordpress.ts:168]: awesome!

**Review by pahud — APPROVED** [review]
